### PR TITLE
Rename parameter readingFrequency

### PR DESCRIPTION
**Pull request by pgan002**
The parameter is not a frequency (number of iterations per unit time) but an interval. Rename both the API parameter and the variable name.

### CODE REVIEW

**Comment by pgan002** [comment]
According to Merriam Webster, an interval is (1) a "space of time between events or states". I think "reading" is ambiguous; it can be a verb. The most accurate term is a measurement done by the sensor. So maybe either:
* `secondsBetweenMeasurements`
* `measurementIntervalSeconds`

**Comment by sbookert** [comment]
@pgan002 yup if you add seconds and measurement it helps a lot

**Comment by sbookert** [comment]
@pgan002 also Note that I added a task to trello to persist these global settings. We lose them when deploying new code bc the vm needs to restart.

**Comment by pgan002** [comment]
That task seems independent from this change, so I will reply in Slack.

**Pull request merged**
